### ISSUE TITLE
Timer "container->cache_frontend_create" doesn't exist.

### ISSUE THREAD

**Issue by nahall** [perryholden/Holdenovi_Profiler#4]
Hello,

I'm trying this module with Magento 2.4.3 and followed the installation instructions. It isn't working and I'm getting this in my PHP error log:
```

PHP message: PHP Fatal error:  Uncaught InvalidArgumentException: Timer "container->cache_frontend_create" doesn't exist. in /home/xxxx/www/vendor/magento/framework/Profiler/Driver/Standard/Stat.php:71

#0 /home/xxxx/www/vendor/magento/framework/Profiler/Driver/Standard.php(172): Magento\Framework\Profiler\Driver\Standard\Stat->stop()
#1 /home/xxxx/www/vendor/magento/framework/Profiler.php(316): Magento\Framework\Profiler\Driver\Standard->stop()
#2 /home/xxxx/www/vendor/magento/framework/App/Cache/Frontend/Factory.php(183): Magento\Framework\Profiler::stop()
#3 /home/xxxx/www/vendor/magento/framework/App/Cache/Frontend/Pool.php(69): Magento\Framework\App\Cache\Frontend\Factory->create()
#4 /home/xxxx/www/vendor/magento/framework/App/Cache/Frontend/Pool.php(151): Magento\Framework\App\Cache\Frontend\Pool->_initialize()
#5 /home/xxxx/www/vendor/magento/framework/App/Cache/Type/FrontendPool.php(87): Magento\Framework\App\Cache\Frontend\Pool->get()
```

I'm wondering if this extension has been updated for Magento 2.4.3. Thanks.

**Comment by perryholden** [comment]
@nahall - Apologies for the delay. I just tried this with Magento 2.4.3-p1, and I cannot duplicate the issue. Can you post which PHP version you are using?

**Comment by perryholden** [comment]
I just noticed that the error is coming from `\Magento\Framework\Profiler\Driver\Standard\Stat` instead of `\Holdenovi\Profiler\Driver\Standard\Stat`. Specifically, this command is responsible for swapping those out: `bin/magento dev:profiler:enable '{"drivers":[{"type":"Holdenovi\\Profiler\\Driver\\Hierarchy"}]}'`. Did you do this step?

**Comment by ioweb-gr** [comment]
@perryholden Same issue here, I did enable it  on 2.4.1 and the same issue occurs.

```
/httpdocs$ m2 dev:profiler:enable '{"drivers":[{"type":"Holdenovi\\Profiler\\Driver\\Hierarchy"}]}'
Type {"drivers":[{"type":"Holdenovi\\Profiler\\Driver\\Hierarchy"}]} is not one of the built-in output types (html, csvfile).
Profiler enabled with {"drivers":[{"type":"Holdenovi\\Profiler\\Driver\\Hierarchy"}]} output.
```

**Comment by perryholden** [comment]
@ioweb-gr - This is not an error as much as a warning. The last line shows that the profiler is enabled. Anything not `html` or `csvfile` will give the warning. Are you getting the same argument exception as the original issue?

**Comment by ioweb-gr** [comment]
Yes getting the same exception as above that's why I bumped into this issue

**Comment by perryholden** [comment]
@ioweb-gr - Thanks. I can't duplicate this on vanilla 2.4.3 or any other version of 2.4. Can you share a bit more about your environment? Do you have any other profiling extensions installed? What PHP version are you running?
